# Generated by Django 5.2.6 on 2025-11-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('st_number', models.TextField()),
                ('st_name', models.TextField()),
                ('apt_num', models.TextField()),
                ('zip_code', models.CharField(max_length=10)),
                ('doB', models.DateField()),
                ('doReg', models.DateField()),
                ('party_affiliation', models.CharField(max_length=2)),
                ('precinct_num', models.CharField(max_length=10)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.IntegerField(default=0)),
            ],
        ),
    ]
