# Generated by Django 5.2.6 on 2025-11-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apt_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
