# Generated by Django 5.2.6 on 2025-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('display_name', models.TextField(blank=True)),
                ('profile_image_url', models.TextField(blank=True)),
                ('bio_text', models.TextField(blank=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
