# Generated by Django 5.2.6 on 2025-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_alter_photo_post_alter_photo_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
